global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webserver'
    static_configs:
      - targets: ['webserver:8080']
  - job_name: 'producer'
    metrics_path: /
    static_configs:
      - targets: ['kafka-producer:8090']
             
